set_property SRC_FILE_INFO {cfile:H:/FPGA_basicproject/ARP/project/project_arp/project_arp.srcs/constrs_1/new/pin.xdc rfile:../../../project_arp.srcs/constrs_1/new/pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V19 [get_ports {ETH_RXD[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W20 [get_ports {ETH_RXD[1]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA20 [get_ports {ETH_RXD[2]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA21 [get_ports {ETH_RXD[3]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W21 [get_ports {ETH_TXD[0]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W22 [get_ports {ETH_TXD[1]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y21 [get_ports {ETH_TXD[2]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y22 [get_ports {ETH_TXD[3]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports ETH_rst]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports ETH_RXC]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V18 [get_ports ETH_RXV]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB21 [get_ports ETH_TXC]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB22 [get_ports ETH_TXV]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports key]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports rstn]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list ETH_RXC_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 48 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {arp_inst/arp_rx_inst/pc_mac[0]} {arp_inst/arp_rx_inst/pc_mac[1]} {arp_inst/arp_rx_inst/pc_mac[2]} {arp_inst/arp_rx_inst/pc_mac[3]} {arp_inst/arp_rx_inst/pc_mac[4]} {arp_inst/arp_rx_inst/pc_mac[5]} {arp_inst/arp_rx_inst/pc_mac[6]} {arp_inst/arp_rx_inst/pc_mac[7]} {arp_inst/arp_rx_inst/pc_mac[8]} {arp_inst/arp_rx_inst/pc_mac[9]} {arp_inst/arp_rx_inst/pc_mac[10]} {arp_inst/arp_rx_inst/pc_mac[11]} {arp_inst/arp_rx_inst/pc_mac[12]} {arp_inst/arp_rx_inst/pc_mac[13]} {arp_inst/arp_rx_inst/pc_mac[14]} {arp_inst/arp_rx_inst/pc_mac[15]} {arp_inst/arp_rx_inst/pc_mac[16]} {arp_inst/arp_rx_inst/pc_mac[17]} {arp_inst/arp_rx_inst/pc_mac[18]} {arp_inst/arp_rx_inst/pc_mac[19]} {arp_inst/arp_rx_inst/pc_mac[20]} {arp_inst/arp_rx_inst/pc_mac[21]} {arp_inst/arp_rx_inst/pc_mac[22]} {arp_inst/arp_rx_inst/pc_mac[23]} {arp_inst/arp_rx_inst/pc_mac[24]} {arp_inst/arp_rx_inst/pc_mac[25]} {arp_inst/arp_rx_inst/pc_mac[26]} {arp_inst/arp_rx_inst/pc_mac[27]} {arp_inst/arp_rx_inst/pc_mac[28]} {arp_inst/arp_rx_inst/pc_mac[29]} {arp_inst/arp_rx_inst/pc_mac[30]} {arp_inst/arp_rx_inst/pc_mac[31]} {arp_inst/arp_rx_inst/pc_mac[32]} {arp_inst/arp_rx_inst/pc_mac[33]} {arp_inst/arp_rx_inst/pc_mac[34]} {arp_inst/arp_rx_inst/pc_mac[35]} {arp_inst/arp_rx_inst/pc_mac[36]} {arp_inst/arp_rx_inst/pc_mac[37]} {arp_inst/arp_rx_inst/pc_mac[38]} {arp_inst/arp_rx_inst/pc_mac[39]} {arp_inst/arp_rx_inst/pc_mac[40]} {arp_inst/arp_rx_inst/pc_mac[41]} {arp_inst/arp_rx_inst/pc_mac[42]} {arp_inst/arp_rx_inst/pc_mac[43]} {arp_inst/arp_rx_inst/pc_mac[44]} {arp_inst/arp_rx_inst/pc_mac[45]} {arp_inst/arp_rx_inst/pc_mac[46]} {arp_inst/arp_rx_inst/pc_mac[47]}]]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {arp_inst/arp_rx_inst/cnt_byte[0]} {arp_inst/arp_rx_inst/cnt_byte[1]} {arp_inst/arp_rx_inst/cnt_byte[2]} {arp_inst/arp_rx_inst/cnt_byte[3]} {arp_inst/arp_rx_inst/cnt_byte[4]} {arp_inst/arp_rx_inst/cnt_byte[5]} {arp_inst/arp_rx_inst/cnt_byte[6]} {arp_inst/arp_rx_inst/cnt_byte[7]}]]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 7 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {arp_inst/arp_rx_inst/op[1]} {arp_inst/arp_rx_inst/op[2]} {arp_inst/arp_rx_inst/op[3]} {arp_inst/arp_rx_inst/op[8]} {arp_inst/arp_rx_inst/op[9]} {arp_inst/arp_rx_inst/op[10]} {arp_inst/arp_rx_inst/op[11]}]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {arp_inst/arp_rx_inst/pc_ip[0]} {arp_inst/arp_rx_inst/pc_ip[1]} {arp_inst/arp_rx_inst/pc_ip[2]} {arp_inst/arp_rx_inst/pc_ip[3]} {arp_inst/arp_rx_inst/pc_ip[4]} {arp_inst/arp_rx_inst/pc_ip[5]} {arp_inst/arp_rx_inst/pc_ip[6]} {arp_inst/arp_rx_inst/pc_ip[7]} {arp_inst/arp_rx_inst/pc_ip[8]} {arp_inst/arp_rx_inst/pc_ip[9]} {arp_inst/arp_rx_inst/pc_ip[10]} {arp_inst/arp_rx_inst/pc_ip[11]} {arp_inst/arp_rx_inst/pc_ip[12]} {arp_inst/arp_rx_inst/pc_ip[13]} {arp_inst/arp_rx_inst/pc_ip[14]} {arp_inst/arp_rx_inst/pc_ip[15]} {arp_inst/arp_rx_inst/pc_ip[16]} {arp_inst/arp_rx_inst/pc_ip[17]} {arp_inst/arp_rx_inst/pc_ip[18]} {arp_inst/arp_rx_inst/pc_ip[19]} {arp_inst/arp_rx_inst/pc_ip[20]} {arp_inst/arp_rx_inst/pc_ip[21]} {arp_inst/arp_rx_inst/pc_ip[22]} {arp_inst/arp_rx_inst/pc_ip[23]} {arp_inst/arp_rx_inst/pc_ip[24]} {arp_inst/arp_rx_inst/pc_ip[25]} {arp_inst/arp_rx_inst/pc_ip[26]} {arp_inst/arp_rx_inst/pc_ip[27]} {arp_inst/arp_rx_inst/pc_ip[28]} {arp_inst/arp_rx_inst/pc_ip[29]} {arp_inst/arp_rx_inst/pc_ip[30]} {arp_inst/arp_rx_inst/pc_ip[31]}]]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {arp_inst/arp_tx_inst/cnt_byte[0]} {arp_inst/arp_tx_inst/cnt_byte[1]} {arp_inst/arp_tx_inst/cnt_byte[2]} {arp_inst/arp_tx_inst/cnt_byte[3]} {arp_inst/arp_tx_inst/cnt_byte[4]} {arp_inst/arp_tx_inst/cnt_byte[5]} {arp_inst/arp_tx_inst/cnt_byte[6]} {arp_inst/arp_tx_inst/cnt_byte[7]}]]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {arp_inst/arp_tx_inst/arp_tx_data[0]} {arp_inst/arp_tx_inst/arp_tx_data[1]} {arp_inst/arp_tx_inst/arp_tx_data[2]} {arp_inst/arp_tx_inst/arp_tx_data[3]} {arp_inst/arp_tx_inst/arp_tx_data[4]} {arp_inst/arp_tx_inst/arp_tx_data[5]} {arp_inst/arp_tx_inst/arp_tx_data[6]} {arp_inst/arp_tx_inst/arp_tx_data[7]}]]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {arp_inst/arp_rx_inst/state[0]} {arp_inst/arp_rx_inst/state[1]} {arp_inst/arp_rx_inst/state[2]} {arp_inst/arp_rx_inst/state[3]} {arp_inst/arp_rx_inst/state[4]}]]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 5 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {arp_inst/arp_tx_inst/state[0]} {arp_inst/arp_tx_inst/state[1]} {arp_inst/arp_tx_inst/state[2]} {arp_inst/arp_tx_inst/state[3]} {arp_inst/arp_tx_inst/state[4]}]]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list arp_inst/arp_rx_inst/arp_rx_done]]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list arp_inst/arp_rx_inst/arp_rx_op]]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list arp_inst/arp_tx_inst/arp_tx_done]]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list arp_ctrl_inst/arp_tx_en]]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list arp_ctrl_inst/arp_tx_op]]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list arp_inst/arp_tx_inst/arp_tx_valid]]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list arp_inst/arp_rx_inst/error]]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets ETH_RXC_IBUF_BUFG]
