set_property PACKAGE_PIN R14 [get_ports resetn_0]
set_property IOSTANDARD LVCMOS33 [get_ports resetn_0]
set_property PACKAGE_PIN V4 [get_ports clk_in1_0]
set_property IOSTANDARD SSTL135 [get_ports clk_in1_0]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets design_1_i/clk_wiz_0/inst/clk_in1_design_1_clk_wiz_0_0] 
