set_property PACKAGE_PIN V19 [get_ports {ETH_RXD[0]}]
set_property PACKAGE_PIN W20 [get_ports {ETH_RXD[1]}]
set_property PACKAGE_PIN AA20 [get_ports {ETH_RXD[2]}]
set_property PACKAGE_PIN AA21 [get_ports {ETH_RXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_RXD[0]}]
set_property PACKAGE_PIN W21 [get_ports {ETH_TXD[0]}]
set_property PACKAGE_PIN W22 [get_ports {ETH_TXD[1]}]
set_property PACKAGE_PIN Y21 [get_ports {ETH_TXD[2]}]
set_property PACKAGE_PIN Y22 [get_ports {ETH_TXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ETH_TXD[0]}]
set_property PACKAGE_PIN U17 [get_ports ETH_rst]
set_property PACKAGE_PIN W19 [get_ports ETH_RXC]
set_property PACKAGE_PIN V18 [get_ports ETH_RXV]
set_property PACKAGE_PIN AB21 [get_ports ETH_TXC]
set_property PACKAGE_PIN AB22 [get_ports ETH_TXV]
set_property PACKAGE_PIN R14 [get_ports key]
set_property PACKAGE_PIN P14 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_rst]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXC]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_RXV]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXC]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_TXV]
set_property IOSTANDARD LVCMOS33 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ETH_RXC_IBUF]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {arp_inst/arp_rx_inst/pc_ip[0]} {arp_inst/arp_rx_inst/pc_ip[1]} {arp_inst/arp_rx_inst/pc_ip[2]} {arp_inst/arp_rx_inst/pc_ip[3]} {arp_inst/arp_rx_inst/pc_ip[4]} {arp_inst/arp_rx_inst/pc_ip[5]} {arp_inst/arp_rx_inst/pc_ip[6]} {arp_inst/arp_rx_inst/pc_ip[7]} {arp_inst/arp_rx_inst/pc_ip[8]} {arp_inst/arp_rx_inst/pc_ip[9]} {arp_inst/arp_rx_inst/pc_ip[10]} {arp_inst/arp_rx_inst/pc_ip[11]} {arp_inst/arp_rx_inst/pc_ip[12]} {arp_inst/arp_rx_inst/pc_ip[13]} {arp_inst/arp_rx_inst/pc_ip[14]} {arp_inst/arp_rx_inst/pc_ip[15]} {arp_inst/arp_rx_inst/pc_ip[16]} {arp_inst/arp_rx_inst/pc_ip[17]} {arp_inst/arp_rx_inst/pc_ip[18]} {arp_inst/arp_rx_inst/pc_ip[19]} {arp_inst/arp_rx_inst/pc_ip[20]} {arp_inst/arp_rx_inst/pc_ip[21]} {arp_inst/arp_rx_inst/pc_ip[22]} {arp_inst/arp_rx_inst/pc_ip[23]} {arp_inst/arp_rx_inst/pc_ip[24]} {arp_inst/arp_rx_inst/pc_ip[25]} {arp_inst/arp_rx_inst/pc_ip[26]} {arp_inst/arp_rx_inst/pc_ip[27]} {arp_inst/arp_rx_inst/pc_ip[28]} {arp_inst/arp_rx_inst/pc_ip[29]} {arp_inst/arp_rx_inst/pc_ip[30]} {arp_inst/arp_rx_inst/pc_ip[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {arp_inst/arp_tx_inst/cnt_byte[0]} {arp_inst/arp_tx_inst/cnt_byte[1]} {arp_inst/arp_tx_inst/cnt_byte[2]} {arp_inst/arp_tx_inst/cnt_byte[3]} {arp_inst/arp_tx_inst/cnt_byte[4]} {arp_inst/arp_tx_inst/cnt_byte[5]} {arp_inst/arp_tx_inst/cnt_byte[6]} {arp_inst/arp_tx_inst/cnt_byte[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {arp_inst/arp_rx_inst/cnt_byte[0]} {arp_inst/arp_rx_inst/cnt_byte[1]} {arp_inst/arp_rx_inst/cnt_byte[2]} {arp_inst/arp_rx_inst/cnt_byte[3]} {arp_inst/arp_rx_inst/cnt_byte[4]} {arp_inst/arp_rx_inst/cnt_byte[5]} {arp_inst/arp_rx_inst/cnt_byte[6]} {arp_inst/arp_rx_inst/cnt_byte[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 5 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {arp_inst/arp_tx_inst/state[0]} {arp_inst/arp_tx_inst/state[1]} {arp_inst/arp_tx_inst/state[2]} {arp_inst/arp_tx_inst/state[3]} {arp_inst/arp_tx_inst/state[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 48 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {arp_inst/arp_rx_inst/pc_mac[0]} {arp_inst/arp_rx_inst/pc_mac[1]} {arp_inst/arp_rx_inst/pc_mac[2]} {arp_inst/arp_rx_inst/pc_mac[3]} {arp_inst/arp_rx_inst/pc_mac[4]} {arp_inst/arp_rx_inst/pc_mac[5]} {arp_inst/arp_rx_inst/pc_mac[6]} {arp_inst/arp_rx_inst/pc_mac[7]} {arp_inst/arp_rx_inst/pc_mac[8]} {arp_inst/arp_rx_inst/pc_mac[9]} {arp_inst/arp_rx_inst/pc_mac[10]} {arp_inst/arp_rx_inst/pc_mac[11]} {arp_inst/arp_rx_inst/pc_mac[12]} {arp_inst/arp_rx_inst/pc_mac[13]} {arp_inst/arp_rx_inst/pc_mac[14]} {arp_inst/arp_rx_inst/pc_mac[15]} {arp_inst/arp_rx_inst/pc_mac[16]} {arp_inst/arp_rx_inst/pc_mac[17]} {arp_inst/arp_rx_inst/pc_mac[18]} {arp_inst/arp_rx_inst/pc_mac[19]} {arp_inst/arp_rx_inst/pc_mac[20]} {arp_inst/arp_rx_inst/pc_mac[21]} {arp_inst/arp_rx_inst/pc_mac[22]} {arp_inst/arp_rx_inst/pc_mac[23]} {arp_inst/arp_rx_inst/pc_mac[24]} {arp_inst/arp_rx_inst/pc_mac[25]} {arp_inst/arp_rx_inst/pc_mac[26]} {arp_inst/arp_rx_inst/pc_mac[27]} {arp_inst/arp_rx_inst/pc_mac[28]} {arp_inst/arp_rx_inst/pc_mac[29]} {arp_inst/arp_rx_inst/pc_mac[30]} {arp_inst/arp_rx_inst/pc_mac[31]} {arp_inst/arp_rx_inst/pc_mac[32]} {arp_inst/arp_rx_inst/pc_mac[33]} {arp_inst/arp_rx_inst/pc_mac[34]} {arp_inst/arp_rx_inst/pc_mac[35]} {arp_inst/arp_rx_inst/pc_mac[36]} {arp_inst/arp_rx_inst/pc_mac[37]} {arp_inst/arp_rx_inst/pc_mac[38]} {arp_inst/arp_rx_inst/pc_mac[39]} {arp_inst/arp_rx_inst/pc_mac[40]} {arp_inst/arp_rx_inst/pc_mac[41]} {arp_inst/arp_rx_inst/pc_mac[42]} {arp_inst/arp_rx_inst/pc_mac[43]} {arp_inst/arp_rx_inst/pc_mac[44]} {arp_inst/arp_rx_inst/pc_mac[45]} {arp_inst/arp_rx_inst/pc_mac[46]} {arp_inst/arp_rx_inst/pc_mac[47]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 5 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {arp_inst/arp_rx_inst/state[0]} {arp_inst/arp_rx_inst/state[1]} {arp_inst/arp_rx_inst/state[2]} {arp_inst/arp_rx_inst/state[3]} {arp_inst/arp_rx_inst/state[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 7 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {arp_inst/arp_rx_inst/op[1]} {arp_inst/arp_rx_inst/op[2]} {arp_inst/arp_rx_inst/op[3]} {arp_inst/arp_rx_inst/op[8]} {arp_inst/arp_rx_inst/op[9]} {arp_inst/arp_rx_inst/op[10]} {arp_inst/arp_rx_inst/op[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {arp_inst/arp_tx_inst/arp_tx_data[0]} {arp_inst/arp_tx_inst/arp_tx_data[1]} {arp_inst/arp_tx_inst/arp_tx_data[2]} {arp_inst/arp_tx_inst/arp_tx_data[3]} {arp_inst/arp_tx_inst/arp_tx_data[4]} {arp_inst/arp_tx_inst/arp_tx_data[5]} {arp_inst/arp_tx_inst/arp_tx_data[6]} {arp_inst/arp_tx_inst/arp_tx_data[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list arp_inst/arp_rx_inst/arp_rx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list arp_inst/arp_rx_inst/arp_rx_op]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list arp_inst/arp_tx_inst/arp_tx_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list arp_ctrl_inst/arp_tx_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list arp_ctrl_inst/arp_tx_op]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list arp_inst/arp_tx_inst/arp_tx_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list arp_inst/arp_rx_inst/error]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets ETH_RXC_IBUF]
